name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


env:
  PRE_COMMIT_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
        os: [ubuntu-latest]
    env:
      PYTHON: ${{ matrix.python-version }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Cache deps
      uses: actions/cache@v2
      with:
        path: |
          ~/.cache/pypoetry/
          ~/.cache/pip/
        key: python${{ matrix.python-version }}-${{ hashFiles('poetry.lock') }}
        restore-keys: python${{ matrix.python-version }}-
    - name: Cache pre-commit deps
      uses: actions/cache@v2
      with:
        path: |
          ~/.cache/pre-commit/
        key: precommit-${{ hashFiles('.pre-commit-config.yaml') }}
        restore-keys: precommit-
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade poetry pre-commit
        poetry install
    - name: Lint
      run: |
        pre-commit run --all-files -v --show-diff-on-failure
        poetry run pytest --dead-fixtures --dup-fixtures --color=yes
        pre-commit gc
    - name: Test with pytest
      run: |
        make test args="--color=yes"
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1.5.0
      with:
        flags: unittests
        env_vars: PYTHON
